### PR TITLE
Suggestions on home page - Closes #145

### LINKED ISSUE #145: broken product images on home under suggestions
screen shot 2015-09-14 at 17 08 29

### PR DESCRIPTION
**Pull request by peter-gerhard**
@lauraluiz @schleichardt 
I added suggestions and static data to HomePageData in order to show the suggestions
I have duplicated messages, that should be moved to a more common location but i think for now its ok.

### CODE REVIEW

File: product-catalog/app/productcatalog/services/CategoryService.java [hunk 1]
```diff
@@ -29,4 +30,12 @@
...
      */
     public boolean categoryIsInNew(final Reference<Category> category);
+
+    /**
+     * Gets a subtree from the given CategoryTree with the given Category as root.
+     * If the given Category is not in the given CategoryTree the returned CategoryTree will be empty.
+     * @param category
+     * @return The Subtree starting at the given Category
+     */
+    public CategoryTree getSubtree(final CategoryTree categoryTree, final Category category);
```
Comment (lauraluiz) [inline product-catalog/app/productcatalog/services/CategoryService.java]: This will be very useful for me, thanks :+1:

**Comment by lauraluiz** [comment]
:+1: I will ignore the hardcoded stuff ;)
